Repository AY1920S1-CS2103T-F11-1/main, pull requests merged in 2019-11, with the labels that each got.

#220 Change user guide 1 nov
  docs/UserGuide.adoc
Labels: documentation

#222 Fix command navigation
  src/main/java/seedu/address/logic/commands/assigncommand/AssignMentorCommand.java
  src/main/java/seedu/address/logic/commands/assigncommand/AssignParticipantCommand.java
  src/main/java/seedu/address/logic/commands/leaderboardcommand/ShowLeaderboardWithRandomCommand.java
  src/main/java/seedu/address/logic/commands/leaderboardcommand/ShowSimpleLeaderboardCommand.java
  src/main/java/seedu/address/logic/commands/removecommand/RemoveMentorCommand.java
  src/main/java/seedu/address/logic/commands/removecommand/RemoveParticipantCommand.java
  src/main/java/seedu/address/logic/commands/scorecommand/AddScoreCommand.java
  src/main/java/seedu/address/logic/commands/scorecommand/ScoreCommand.java
  src/main/java/seedu/address/logic/commands/scorecommand/SetScoreCommand.java
  src/main/java/seedu/address/logic/commands/scorecommand/SubtractScoreCommand.java
  src/main/java/seedu/address/logic/commands/viewcommand/ViewMentorCommand.java
  src/main/java/seedu/address/logic/commands/viewcommand/ViewParticipantCommand.java
  src/main/java/seedu/address/logic/commands/viewcommand/ViewTeamCommand.java
  src/main/java/seedu/address/logic/parser/AlfredParser.java
Labels: priority.High, type.Bug

#240 Implement Multiple Undo/Redo Feature
  src/main/java/seedu/address/logic/commands/historycommand/RedoCommand.java
  src/main/java/seedu/address/logic/commands/historycommand/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AlfredParser.java
  src/main/java/seedu/address/logic/parser/historycommandparser/RedoCommandParser.java
  src/main/java/seedu/address/logic/parser/historycommandparser/UndoCommandParser.java
  src/main/java/seedu/address/model/CommandRecord.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelHistory.java
  src/main/java/seedu/address/model/ModelHistoryManager.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/CommandRecordCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/historycommand/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/historycommand/UndoCommandTest.java
  src/test/java/seedu/address/logic/parser/historycommandparser/RedoCommandParserTest.java
  src/test/java/seedu/address/logic/parser/historycommandparser/UndoCommandParserTest.java
  src/test/java/seedu/address/model/ModelHistoryManagerTest.java
  src/test/java/seedu/address/stub/ModelManagerStub.java
Labels: priority.High, type.Story

#279 Deprecate ab3 storage
  src/main/java/seedu/address/logic/commands/historycommand/HistoryCommand.java
  src/main/java/seedu/address/logic/parser/AlfredParser.java
  src/main/java/seedu/address/logic/parser/historycommandparser/HistoryCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/AlfredStorageManager.java
  src/main/java/seedu/address/storage/JsonAdaptedParticipant.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/exceptions/LoadException.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.High, type.Bug, type.Story

#241 Implement capacity of 50 for CommandHistoryManager
  src/main/java/seedu/address/model/CommandHistoryManager.java
Labels: priority.Medium, type.Enhancement

#283 Change to use Alt Modifier for Command History Navigation Feature
  src/main/java/seedu/address/model/CommandHistoryManager.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.High, type.Story

#287 Update developer guide v1.4
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/diagrams/CommandHistoryNavigationArrowKeyInvocation.puml
  docs/diagrams/CommandHistoryNavigationSettingofCommandString.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/diagrams/UndoSequenceDiagramExecutionOfUndo.puml
  docs/diagrams/UndoSequenceDiagramUpdateHistory.puml
  docs/diagrams/UpdateModelHistoryStateSequenceDiagram.puml
  docs/images/CommandHistoryNavigationArrowKeyInvocation.png
  docs/images/CommandHistoryNavigationSettingofCommandString.png
  docs/images/ParticipantListJson.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagramExecutionOfUndo.png
  docs/images/UndoSequenceDiagramUpdateHistory.png
Labels: documentation, priority.High

#298 Refactorscore
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/scorecommand/AddScoreCommand.java
  src/main/java/seedu/address/logic/commands/scorecommand/SetScoreCommand.java
  src/main/java/seedu/address/logic/commands/scorecommand/SubtractScoreCommand.java
  src/main/java/seedu/address/logic/parser/AlfredParser.java
  src/main/java/seedu/address/logic/parser/scorecommandparser/AddScoreCommandParser.java
  src/main/java/seedu/address/logic/parser/scorecommandparser/ResetScoreCommandParser.java
  src/main/java/seedu/address/logic/parser/scorecommandparser/ScoreCommandAllocator.java
  src/main/java/seedu/address/logic/parser/scorecommandparser/ScoreCommandParser.java
  src/main/java/seedu/address/logic/parser/scorecommandparser/SetScoreCommandParser.java
  src/main/java/seedu/address/logic/parser/scorecommandparser/SubtractScoreCommandParser.java
  src/test/java/seedu/address/logic/parser/scorecommandparser/AddScoreCommandParserTest.java
  src/test/java/seedu/address/logic/parser/scorecommandparser/ResetScoreCommandParserTest.java
  src/test/java/seedu/address/logic/parser/scorecommandparser/ScoreCommandAllocatorTest.java
  src/test/java/seedu/address/logic/parser/scorecommandparser/ScoreCommandParserTest.java
  src/test/java/seedu/address/logic/parser/scorecommandparser/SetScoreCommandParserTest.java
  src/test/java/seedu/address/logic/parser/scorecommandparser/SubtractScoreCommandParserTest.java
Labels: enhancement

#304 user guide fix
  docs/UserGuide.adoc
Labels: documentation

#302 Fix undo redo ui response
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/historycommand/RedoCommand.java
  src/main/java/seedu/address/logic/commands/historycommand/UndoCommand.java
  src/test/java/seedu/address/logic/commands/historycommand/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/historycommand/UndoCommandTest.java
Labels: priority.High, type.Enhancement

#314 Ugfixpt2
  docs/UserGuide.adoc
Labels: documentation

#317 Update user guide v1.4
  docs/UserGuide.adoc
Labels: Update UG, priority.High

#340 Create final tests
  src/main/java/seedu/address/model/CommandHistoryManager.java
  src/main/java/seedu/address/model/CommandRecord.java
  src/test/java/seedu/address/logic/commands/historycommand/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/historycommand/UndoCommandTest.java
  src/test/java/seedu/address/model/CommandHistoryManagerTest.java
  src/test/java/seedu/address/model/CommandRecordTest.java
Labels: type.Enhancement

#341 Update user guide (Undo/Redo/History)
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/HistoryCommandExampleOutput.png
  docs/images/HistoryCommandExampleOutputAfterUndo.png
  docs/images/UndoRedoExplanation.png
Labels: documentation, priority.Medium, type.Chore

#329 General Improvements for Code
  src/main/java/seedu/address/logic/commands/leaderboardcommand/LeaderboardCommand.java
  src/main/java/seedu/address/logic/commands/scorecommand/AddScoreCommand.java
  src/main/java/seedu/address/logic/commands/scorecommand/SetScoreCommand.java
  src/main/java/seedu/address/logic/commands/scorecommand/SubtractScoreCommand.java
  src/main/java/seedu/address/logic/commands/topteamscommand/SimpleTopTeamsCommand.java
  src/main/java/seedu/address/logic/commands/topteamscommand/TopTeamsCommand.java
  src/main/java/seedu/address/logic/commands/topteamscommand/TopTeamsRandomCommand.java
  src/main/java/seedu/address/logic/parser/LeaderboardCommandParser.java
  src/main/java/seedu/address/logic/parser/TopTeamsCommandParser.java
  src/main/java/seedu/address/logic/parser/scorecommandparser/ScoreCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: enhancement

#346 Update developer guide and user guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/HistoryCommandRendering.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagramExecutionOfUndo.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/HistoryCommandRendering.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagramExecutionOfUndo.png
Labels: documentation

#345 Finalise Scoring Section in Dev Guide
  docs/DeveloperGuide.adoc
  docs/diagrams/ScoringSequenceDiagram.puml
  docs/diagrams/TieBreakActivityDiagram.puml
  docs/images/ScoringClassDiagram.png
  docs/images/ScoringSequenceDiagram.png
  docs/images/TieBreakActivityDiagram.png
  docs/team/abhimanyadav.adoc
  docs/team/abhimanyadav.pdf
Labels: documentation

#337 Near last fixes
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandUtils.java
  src/main/java/seedu/address/logic/commands/assigncommand/AssignMentorCommand.java
  src/main/java/seedu/address/logic/commands/assigncommand/AssignParticipantCommand.java
  src/main/java/seedu/address/logic/commands/csvcommand/ImportCommand.java
  src/main/java/seedu/address/logic/commands/historycommand/HistoryCommand.java
  src/main/java/seedu/address/logic/commands/historycommand/RedoCommand.java
  src/main/java/seedu/address/logic/commands/historycommand/UndoCommand.java
  src/main/java/seedu/address/logic/commands/removecommand/RemoveMentorCommand.java
  src/main/java/seedu/address/logic/commands/removecommand/RemoveParticipantCommand.java
  src/main/java/seedu/address/logic/commands/topteamscommand/SimpleTopTeamsCommand.java
  src/main/java/seedu/address/logic/commands/topteamscommand/TopTeamsRandomCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelHistory.java
  src/main/java/seedu/address/model/ModelHistoryManager.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug, type.Chore, type.Story

#355 Update Home and Help commands for Command History Navigation Feature
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/UiIntro.png
  docs/team/brianyen.adoc
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/HomeCommand.java
  src/main/java/seedu/address/logic/parser/AlfredParser.java
Labels: bug, severity.Medium

#358 Update and Finalise PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/brianyen.adoc
  docs/team/brianyen.pdf
Labels: documentation, priority.High

#365 Update ppp
  docs/DeveloperGuide.adoc
Labels: priority.High, type.Story

#367 Standardise dg
  docs/DeveloperGuide.adoc
Labels: documentation, priority.High

#369 Standardise dg
  docs/DeveloperGuide.adoc
Labels: documentation, priority.High

#368 Edit to Alfred Documentation
  docs/DeveloperGuide.adoc
  docs/team/abhimanyadav.pdf
  src/main/java/seedu/address/logic/commands/leaderboardcommand/LeaderboardCommand.java
  src/main/java/seedu/address/logic/commands/leaderboardcommand/LeaderboardWithRandomCommand.java
  src/main/java/seedu/address/logic/commands/leaderboardcommand/SimpleLeaderboardCommand.java
  src/main/java/seedu/address/logic/commands/topteamscommand/SimpleTopTeamsCommand.java
  src/main/java/seedu/address/logic/commands/topteamscommand/TopTeamsCommand.java
  src/main/java/seedu/address/logic/commands/topteamscommand/TopTeamsRandomCommand.java
Labels: documentation, help wanted

#375 Miscellaneous Changes to Help Command and DG
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/CommandUtils.java
  src/main/java/seedu/address/logic/commands/leaderboardcommand/LeaderboardCommand.java
  src/main/java/seedu/address/logic/commands/topteamscommand/TopTeamsCommand.java
  src/main/java/seedu/address/model/entity/SubjectName.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: enhancement
