Repository AY1920S1-CS2103T-F11-1/main, pull requests merged in 2019-10, with the labels that each got.

#78 Update storage
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/entity/Name.java
  src/main/java/seedu/address/model/entity/ProjectType.java
  src/main/java/seedu/address/model/entity/SubjectName.java
  src/main/java/seedu/address/storage/AlfredStorageManager.java
  src/main/java/seedu/address/storage/JsonAdaptedParticipant.java
  src/main/java/seedu/address/storage/JsonMentorListStorage.java
  src/main/java/seedu/address/storage/JsonParticipantListStorage.java
  src/main/java/seedu/address/storage/JsonTeamListStorage.java
  src/test/data/JsonMentorListStorageTest/invalidAndValidMentorList.json
  src/test/data/JsonMentorListStorageTest/invalidMentorList.json
  src/test/data/JsonMentorListStorageTest/notJsonFormatMentorList.json
  src/test/data/JsonParticipantListStorageTest/invalidAndValidParticipantList.json
  src/test/data/JsonParticipantListStorageTest/invalidParticipantList.json
  src/test/data/JsonParticipantListStorageTest/notJsonFormatParticipantList.json
  src/test/data/JsonTeamListStorageTest/invalidAndValidTeamList.json
  src/test/data/JsonTeamListStorageTest/invalidTeamList.json
  src/test/data/JsonTeamListStorageTest/notJsonFormatTeamList.json
  src/test/java/seedu/address/storage/AlfredStorageManagerTest.java
  src/test/java/seedu/address/storage/JsonMentorListStorageTest.java
  src/test/java/seedu/address/storage/JsonParticipantListStorageTest.java
  src/test/java/seedu/address/storage/JsonTeamListStorageTest.java
  src/test/java/seedu/address/testutil/TypicalMentors.java
  src/test/java/seedu/address/testutil/TypicalParticipants.java
  src/test/java/seedu/address/testutil/TypicalTeams.java
Labels: priority.High, type.Story

#79 Implemented tests for commands
  src/main/java/seedu/address/logic/commands/editcommand/EditParticipantCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/commands/listcommand/ListCommand.java
  src/main/java/seedu/address/logic/commands/listcommand/ListMentorCommand.java
  src/main/java/seedu/address/logic/commands/listcommand/ListParticipantCommand.java
  src/main/java/seedu/address/logic/commands/listcommand/ListTeamCommand.java
  src/main/java/seedu/address/logic/commands/viewcommand/ViewCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/entity/Participant.java
  src/main/java/seedu/address/model/entitylist/MentorList.java
  src/main/java/seedu/address/model/entitylist/ParticipantList.java
  src/main/java/seedu/address/model/entitylist/ReadOnlyEntityList.java
  src/main/java/seedu/address/model/entitylist/TeamList.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/addcommand/AddMentorCommandTest.java
  src/test/java/seedu/address/logic/commands/addcommand/AddParticipantCommandTest.java
  src/test/java/seedu/address/logic/commands/addcommand/AddTeamCommandTest.java
  src/test/java/seedu/address/logic/commands/deletecommand/DeleteMentorCommandTest.java
  src/test/java/seedu/address/logic/commands/deletecommand/DeleteParticipantCommandTest.java
  src/test/java/seedu/address/logic/commands/deletecommand/DeleteTeamCommandTest.java
  src/test/java/seedu/address/logic/commands/editcommand/EditMentorCommandTest.java
  src/test/java/seedu/address/logic/commands/editcommand/EditMentorDescriptorTest.java
  src/test/java/seedu/address/logic/commands/editcommand/EditParticipantCommandTest.java
  src/test/java/seedu/address/logic/commands/editcommand/EditParticipantDescriptorTest.java
  src/test/java/seedu/address/logic/commands/editcommand/EditTeamCommandTest.java
  src/test/java/seedu/address/logic/commands/editcommand/EditTeamDescriptorTest.java
  src/test/java/seedu/address/logic/commands/listcommand/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/listcommand/ListMentorCommandTest.java
  src/test/java/seedu/address/logic/commands/listcommand/ListParticipantCommandTest.java
  src/test/java/seedu/address/logic/commands/listcommand/ListTeamCommandTest.java
  src/test/java/seedu/address/logic/commands/viewcommand/ViewMentorCommandTest.java
  src/test/java/seedu/address/logic/commands/viewcommand/ViewParticipantCommandTest.java
  src/test/java/seedu/address/logic/commands/viewcommand/ViewTeamCommandTest.java
  src/test/java/seedu/address/stub/ModelManagerStub.java
  src/test/java/seedu/address/testutil/EditMentorDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditParticipantDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditTeamDescriptorBuilder.java
  src/test/java/seedu/address/testutil/MentorBuilder.java
  src/test/java/seedu/address/testutil/ParticipantBuilder.java
  src/test/java/seedu/address/testutil/TeamBuilder.java
  src/test/java/seedu/address/testutil/TypicalIds.java
Labels: status.Ongoing

#86 Implement find command
  src/main/java/seedu/address/commons/Predicates.java
  src/main/java/seedu/address/logic/commands/findcommand/FindCommand.java
  src/main/java/seedu/address/logic/commands/findcommand/FindMentorCommand.java
  src/main/java/seedu/address/logic/commands/findcommand/FindParticipantCommand.java
  src/main/java/seedu/address/logic/commands/findcommand/FindTeamCommand.java
  src/main/java/seedu/address/logic/parser/AlfredParser.java
  src/main/java/seedu/address/logic/parser/findcommandparser/FindMentorCommandParser.java
  src/main/java/seedu/address/logic/parser/findcommandparser/FindParticipantCommandParser.java
  src/main/java/seedu/address/logic/parser/findcommandparser/FindTeamCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/entitylist/MentorList.java
  src/main/java/seedu/address/model/entitylist/ParticipantList.java
  src/main/java/seedu/address/model/entitylist/TeamList.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/entitylist/MentorListTest.java
  src/test/java/seedu/address/model/entitylist/ParticipantListTest.java
  src/test/java/seedu/address/model/entitylist/TeamListTest.java
  src/test/java/seedu/address/testutil/TypicalParticipants.java
Labels: priority.High, type.Enhancement

#107 Implement undo command
  src/main/java/seedu/address/logic/commands/undocommand/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AlfredParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: priority.High, status.Ongoing, type.Story

#123 Fix storage bugs
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/entity/Team.java
  src/main/java/seedu/address/model/entitylist/MentorList.java
  src/main/java/seedu/address/storage/AlfredStorage.java
  src/main/java/seedu/address/storage/AlfredStorageManager.java
  src/main/java/seedu/address/storage/JsonAdaptedMentor.java
  src/main/java/seedu/address/storage/JsonAdaptedTeam.java
  src/main/java/seedu/address/storage/JsonMentorListStorage.java
  src/main/java/seedu/address/storage/JsonParticipantListStorage.java
  src/main/java/seedu/address/storage/JsonSerializableMentorList.java
  src/main/java/seedu/address/storage/JsonSerializableParticipantList.java
  src/main/java/seedu/address/storage/JsonSerializableTeamList.java
  src/main/java/seedu/address/storage/JsonTeamListStorage.java
  src/main/java/seedu/address/storage/MentorListStorage.java
  src/main/java/seedu/address/storage/ParticipantListStorage.java
  src/main/java/seedu/address/storage/TeamListStorage.java
Labels: priority.High, type.Story

#124 Fix problem of default values populating teamlist.json and write edge test cases
  src/test/java/seedu/address/storage/JsonTeamListStorageTest.java
  src/test/java/seedu/address/testutil/TypicalMentors.java
  src/test/java/seedu/address/testutil/TypicalParticipants.java
  src/test/java/seedu/address/testutil/TypicalTeams.java
Labels: priority.High, type.Enhancement, type.Story

#127 Enhance Standardisation of Commands
  src/main/java/seedu/address/logic/commands/addcommand/AddCommand.java
  src/main/java/seedu/address/logic/commands/addcommand/AddMentorCommand.java
  src/main/java/seedu/address/logic/commands/addcommand/AddParticipantCommand.java
  src/main/java/seedu/address/logic/commands/addcommand/AddTeamCommand.java
  src/main/java/seedu/address/logic/commands/deletecommand/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/deletecommand/DeleteMentorCommand.java
  src/main/java/seedu/address/logic/commands/deletecommand/DeleteParticipantCommand.java
  src/main/java/seedu/address/logic/commands/deletecommand/DeleteTeamCommand.java
  src/main/java/seedu/address/logic/commands/editcommand/EditCommand.java
  src/main/java/seedu/address/logic/commands/editcommand/EditMentorCommand.java
  src/main/java/seedu/address/logic/commands/editcommand/EditParticipantCommand.java
  src/main/java/seedu/address/logic/commands/editcommand/EditTeamCommand.java
  src/main/java/seedu/address/logic/commands/listcommand/ListCommand.java
  src/main/java/seedu/address/logic/commands/viewcommand/ViewCommand.java
  src/main/java/seedu/address/logic/commands/viewcommand/ViewMentorCommand.java
  src/main/java/seedu/address/logic/commands/viewcommand/ViewParticipantCommand.java
  src/main/java/seedu/address/logic/commands/viewcommand/ViewTeamCommand.java
  src/main/java/seedu/address/logic/parser/AlfredParser.java
  src/main/java/seedu/address/logic/parser/AlfredParserUtil.java
  src/main/java/seedu/address/logic/parser/CommandAllocator.java
  src/main/java/seedu/address/logic/parser/addcommandparser/AddCommandAllocator.java
  src/main/java/seedu/address/logic/parser/deletecommandparser/DeleteCommandAllocator.java
  src/main/java/seedu/address/logic/parser/deletecommandparser/DeleteMentorCommandParser.java
  src/main/java/seedu/address/logic/parser/deletecommandparser/DeleteParticipantCommandParser.java
  src/main/java/seedu/address/logic/parser/deletecommandparser/DeleteTeamCommandParser.java
  src/main/java/seedu/address/logic/parser/editcommandparser/EditCommandAllocator.java
  src/main/java/seedu/address/logic/parser/editcommandparser/EditMentorCommandParser.java
  src/main/java/seedu/address/logic/parser/editcommandparser/EditParticipantCommandParser.java
  src/main/java/seedu/address/logic/parser/editcommandparser/EditTeamCommandParser.java
  src/main/java/seedu/address/logic/parser/viewcommandparser/ViewCommandAllocator.java
  src/main/java/seedu/address/logic/parser/viewcommandparser/ViewMentorCommandParser.java
  src/main/java/seedu/address/logic/parser/viewcommandparser/ViewParticipantCommandParser.java
  src/main/java/seedu/address/logic/parser/viewcommandparser/ViewTeamCommandParser.java
Labels: type.Enhancement

#87 Feat/bulk registration
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/csvcommand/ExportCommand.java
  src/main/java/seedu/address/logic/commands/csvcommand/ExportMentorCommand.java
  src/main/java/seedu/address/logic/commands/csvcommand/ExportParticipantCommand.java
  src/main/java/seedu/address/logic/commands/csvcommand/ExportTeamCommand.java
  src/main/java/seedu/address/logic/commands/csvcommand/ImportCommand.java
  src/main/java/seedu/address/logic/commands/csvcommand/csvutil/CsvUtil.java
  src/main/java/seedu/address/logic/commands/csvcommand/csvutil/ErrorTracker.java
  src/main/java/seedu/address/logic/parser/AlfredParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/csvcommandparser/ExportCommandParser.java
  src/main/java/seedu/address/logic/parser/csvcommandparser/ImportCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/entity/Id.java
  src/main/java/seedu/address/model/entity/Location.java
  src/main/java/seedu/address/model/entity/Name.java
  src/main/java/seedu/address/model/entity/Phone.java
  src/main/java/seedu/address/model/entity/Team.java
  src/main/java/seedu/address/model/entitylist/EntityList.java
  src/main/java/seedu/address/model/entitylist/MentorList.java
  src/main/java/seedu/address/model/entitylist/ParticipantList.java
  src/main/java/seedu/address/model/entitylist/ReadOnlyEntityList.java
  src/main/java/seedu/address/model/entitylist/TeamList.java
  src/test/data/CsvUtilTest/ExpectedEntities.csv
  src/test/data/CsvUtilTest/ExpectedMentors.csv
  src/test/data/CsvUtilTest/ExpectedMentorsAppended.csv
  src/test/data/CsvUtilTest/ExpectedParticipants.csv
  src/test/data/CsvUtilTest/ExpectedParticipantsAppended.csv
  src/test/data/CsvUtilTest/ExpectedTeams.csv
  src/test/data/CsvUtilTest/ExpectedTeamsAppended.csv
  src/test/data/CsvUtilTest/ImportEntities.csv
  src/test/data/CsvUtilTest/InvalidFormat.csv
  src/test/data/CsvUtilTest/MissingEntity.csv
  src/test/data/CsvUtilTest/TeamFirstValid.csv
  src/test/java/seedu/address/logic/commands/csvcommand/ExportCommandTest.java
  src/test/java/seedu/address/logic/commands/csvcommand/ExportMentorCommandTest.java
  src/test/java/seedu/address/logic/commands/csvcommand/ExportParticipantCommandTest.java
  src/test/java/seedu/address/logic/commands/csvcommand/ExportTeamCommandTest.java
  src/test/java/seedu/address/logic/commands/csvcommand/ImportCommandTest.java
  src/test/java/seedu/address/logic/commands/csvcommand/csvutil/CsvUtilTest.java
  src/test/java/seedu/address/logic/commands/csvcommand/csvutil/ErrorTrackerTest.java
  src/test/java/seedu/address/logic/parser/cvscommandparser/ExportCommandParserTest.java
  src/test/java/seedu/address/logic/parser/cvscommandparser/ImportCommandParserTest.java
  src/test/java/seedu/address/model/entity/IdTest.java
  src/test/java/seedu/address/stub/ModelManagerStub.java
  src/test/java/seedu/address/testutil/FileUtil.java
  src/test/java/seedu/address/testutil/TestUtil.java
Labels: enhancement, priority.High, type.Epic

#152 Update developer guide (Storage)
  docs/DeveloperGuide.adoc
  docs/diagrams/AlfredStorageClassDiagram.puml
  docs/images/AlfredStorageClassDiagram.png
Labels: documentation

#158 Update ID.java regex and solve empty EntityList in JSON bug
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/entity/Id.java
Labels: type.Bug

#171 Revert "Updated ViewCommand, Refactored ListCommands, Other minor updates"
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/Predicates.java
  src/main/java/seedu/address/commons/util/PrefixUtil.java
  src/main/java/seedu/address/logic/commands/findcommand/FindCommand.java
  src/main/java/seedu/address/logic/commands/listcommand/ListCommand.java
  src/main/java/seedu/address/logic/commands/listcommand/ListMentorCommand.java
  src/main/java/seedu/address/logic/commands/listcommand/ListParticipantCommand.java
  src/main/java/seedu/address/logic/commands/listcommand/ListTeamCommand.java
  src/main/java/seedu/address/logic/commands/viewcommand/ViewCommand.java
  src/main/java/seedu/address/logic/commands/viewcommand/ViewMentorCommand.java
  src/main/java/seedu/address/logic/commands/viewcommand/ViewParticipantCommand.java
  src/main/java/seedu/address/logic/commands/viewcommand/ViewTeamCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/entity/Entity.java
  src/main/java/seedu/address/model/entity/Issue.java
  src/main/java/seedu/address/model/entity/Mentor.java
  src/main/java/seedu/address/model/entity/Participant.java
  src/main/java/seedu/address/model/entity/Team.java
  src/main/java/seedu/address/ui/EntityCard.java
  src/main/java/seedu/address/ui/EntityListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/listcommand/ListCommandTest.java
  src/test/java/seedu/address/stub/ModelManagerStub.java
Labels: type.Bug

#173 Update Undo Feature
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/TrackableState.java
  src/main/java/seedu/address/logic/commands/addcommand/AddCommand.java
  src/main/java/seedu/address/logic/commands/csvcommand/ImportCommand.java
  src/main/java/seedu/address/logic/commands/deletecommand/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/editcommand/EditCommand.java
  src/main/java/seedu/address/logic/commands/undocommand/HistoryCommand.java
  src/main/java/seedu/address/logic/commands/undocommand/UndoCommand.java
  src/main/java/seedu/address/model/CommandRecord.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelHistory.java
  src/main/java/seedu/address/model/ModelHistoryManager.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/CommandRecordCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/model/ModelHistoryManagerTest.java
Labels: priority.High, type.Story

#175 Implement redo
  src/main/java/seedu/address/logic/commands/historycommand/HistoryCommand.java
  src/main/java/seedu/address/logic/commands/historycommand/RedoCommand.java
  src/main/java/seedu/address/logic/commands/historycommand/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AlfredParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelHistoryManager.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: priority.High, type.Story

#178 Update undo redo tests
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/historycommand/HistoryCommand.java
  src/main/java/seedu/address/logic/commands/historycommand/RedoCommand.java
  src/main/java/seedu/address/logic/commands/historycommand/UndoCommand.java
  src/main/java/seedu/address/model/ModelHistoryManager.java
  src/test/java/seedu/address/logic/commands/historycommand/HistoryCommandTest.java
  src/test/java/seedu/address/logic/commands/historycommand/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/historycommand/UndoCommandTest.java
  src/test/java/seedu/address/model/ModelHistoryManagerTest.java
  src/test/java/seedu/address/model/ModelHistoryRecordTest.java
  src/test/java/seedu/address/stub/ModelManagerStub.java
Labels: priority.Medium, type.Story

#135 Feature judging
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/scorecommand/AddScoreCommand.java
  src/main/java/seedu/address/logic/commands/scorecommand/ScoreCommand.java
  src/main/java/seedu/address/logic/commands/scorecommand/SetScoreCommand.java
  src/main/java/seedu/address/logic/commands/scorecommand/SubtractScoreCommand.java
  src/main/java/seedu/address/logic/parser/AlfredParser.java
  src/main/java/seedu/address/logic/parser/AlfredParserUtil.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/addcommandparser/AddCommandAllocator.java
  src/main/java/seedu/address/logic/parser/scorecommandparser/AddScoreCommandParser.java
  src/main/java/seedu/address/logic/parser/scorecommandparser/ResetScoreCommandParser.java
  src/main/java/seedu/address/logic/parser/scorecommandparser/ScoreCommandAllocator.java
  src/main/java/seedu/address/logic/parser/scorecommandparser/SetScoreCommandParser.java
  src/main/java/seedu/address/logic/parser/scorecommandparser/SubtractScoreCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/entity/Score.java
  src/test/data/CsvUtilTest/InvalidFormat_Error.csv
  src/test/data/CsvUtilTest/MissingEntity_Error.csv
Labels: status.Ongoing

#190 Implement command navigation
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/addcommand/AddMentorCommand.java
  src/main/java/seedu/address/logic/commands/addcommand/AddParticipantCommand.java
  src/main/java/seedu/address/logic/commands/addcommand/AddTeamCommand.java
  src/main/java/seedu/address/logic/commands/csvcommand/ExportCommand.java
  src/main/java/seedu/address/logic/commands/csvcommand/ExportMentorCommand.java
  src/main/java/seedu/address/logic/commands/csvcommand/ExportParticipantCommand.java
  src/main/java/seedu/address/logic/commands/csvcommand/ExportTeamCommand.java
  src/main/java/seedu/address/logic/commands/csvcommand/ImportCommand.java
  src/main/java/seedu/address/logic/commands/deletecommand/DeleteMentorCommand.java
  src/main/java/seedu/address/logic/commands/deletecommand/DeleteParticipantCommand.java
  src/main/java/seedu/address/logic/commands/deletecommand/DeleteTeamCommand.java
  src/main/java/seedu/address/logic/commands/editcommand/EditMentorCommand.java
  src/main/java/seedu/address/logic/commands/editcommand/EditParticipantCommand.java
  src/main/java/seedu/address/logic/commands/editcommand/EditTeamCommand.java
  src/main/java/seedu/address/logic/commands/findcommand/FindMentorCommand.java
  src/main/java/seedu/address/logic/commands/findcommand/FindParticipantCommand.java
  src/main/java/seedu/address/logic/commands/findcommand/FindTeamCommand.java
  src/main/java/seedu/address/logic/commands/historycommand/HistoryCommand.java
  src/main/java/seedu/address/logic/commands/historycommand/RedoCommand.java
  src/main/java/seedu/address/logic/commands/historycommand/UndoCommand.java
  src/main/java/seedu/address/logic/commands/listcommand/ListMentorCommand.java
  src/main/java/seedu/address/logic/commands/listcommand/ListParticipantCommand.java
  src/main/java/seedu/address/logic/commands/listcommand/ListTeamCommand.java
  src/main/java/seedu/address/logic/parser/AlfredParser.java
  src/main/java/seedu/address/model/CommandHistory.java
  src/main/java/seedu/address/model/CommandHistoryManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/stub/ModelManagerStub.java
Labels: priority.High, status.Ongoing, type.Story

#202 Update user guide v1.3
  docs/UserGuide.adoc
  docs/images/HistoryCommandExampleOutput.png
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.High, type.Story

#134 Feature leaderboard
  src/main/java/seedu/address/commons/Comparators.java
  src/main/java/seedu/address/commons/util/LeaderboardUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/SimpleTopTeamsCommand.java
  src/main/java/seedu/address/logic/commands/TopTeamsCommand.java
  src/main/java/seedu/address/logic/commands/TopTeamsRandomCommand.java
  src/main/java/seedu/address/logic/commands/leaderboardcommand/LeaderboardCommand.java
  src/main/java/seedu/address/logic/commands/leaderboardcommand/ShowLeaderboardWithRandomCommand.java
  src/main/java/seedu/address/logic/commands/leaderboardcommand/ShowSimpleLeaderboardCommand.java
  src/main/java/seedu/address/logic/parser/AlfredParser.java
  src/main/java/seedu/address/logic/parser/AlfredParserUtil.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/GetTopTeamsCommandParser.java
  src/main/java/seedu/address/logic/parser/ShowLeaderBoardCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/entity/CommandType.java
  src/main/java/seedu/address/model/entity/PrefixType.java
  src/main/java/seedu/address/ui/CommandRecordCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/data/CsvUtilTest/ExpectedEntities.csv
  src/test/data/CsvUtilTest/ExpectedTeams.csv
  src/test/data/CsvUtilTest/ExpectedTeamsAppended.csv
  src/test/data/CsvUtilTest/ImportEntities.csv
  src/test/data/CsvUtilTest/TeamFirstValid.csv
  src/test/java/seedu/address/testutil/TypicalTeams.java
Labels: type.Enhancement
